server:
  port: 8189
  servlet:
    context-path: /spring-market-core
    session:
      spring:
        datasource:
          driver-class-name: org.h2.Driver
          url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
          username: sa
          password:
      jpa:
        show-sql: true
        properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect

      h2:
        console:
          enable: true
          setting:
            web-allow-others: false

  url: http://localhost:8189/spring-market-core/
  read-timeout: 10000
  write-timeout: 5000
  connection-timeout: 5000