server:
  port: 8189
  servlet:
    context-path: /spring
    session:
      spring:
        datasource:
          driver-class-name: org.h2.Driver
          url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
          username: sa
          password:
      jpa:
        show-sql: true
        properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect

      h2:
        console:
          enable: true
          setting:
            web-allow-others: false

  jwt:
    secret: sr;l4ge559835t89gj2w094j0qfj9fj0q9j09
    lifetime: 36000000