server:
  port: 8189
  servlet:
    context-path: /spring-market-carts
integrations:
  url: http://localhost:8190/spring-market-cart/
  read-timeout: 10000
  write-timeout: 5000
  connection-timeout: 5000
  cart-service:
    cart-prefix: spring_cart